import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import Navbar from "./Navbar";
import { marked } from "marked";

function CareerPathDetails() {
  const { path } = useParams();
  const [roadmap, setRoadmap] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchRoadmap() {
      setLoading(true);

      const prompt = `
You are an expert career advisor and curriculum designer.
Generate a complete, end-to-end learning roadmap for the career path "${decodeURIComponent(
        path
      )}" using only courses from this catalog: JavaScript, HTML, CSS, Python, SQL, Java, DevOps, Machine Learning, Data Structures, Algorithms, Cloud, React, Node.js, Cybersecurity, etc.
List the steps from beginner to advanced, with each step as a heading and a short description of what the learner should achieve or focus on at that stage. Include at least 6 steps, and make it actionable and easy to follow. Do not use a flow diagram or Mermaid code. Respond in markdown.
`;

      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent?key=`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] }),
        }
      );
      const data = await response.json();
      const text =
        data?.candidates?.[0]?.content?.parts?.[0]?.text ||
        "No roadmap found.";
      setRoadmap(text);
      setLoading(false);
    }
    fetchRoadmap();
  }, [path]);

  return (
    <div>
      <Navbar page="career-paths" />
      <div
        style={{
          maxWidth: 900,
          margin: "40px auto",
          background: "#fff",
          borderRadius: 18,
          boxShadow: "0 4px 32px #2563eb22",
          padding: 40,
        }}
      >
        <h2
          style={{
            color: "#2563eb",
            marginBottom: 24,
            fontWeight: 800,
            letterSpacing: 1,
            fontSize: 32,
            textAlign: "center",
          }}
        >
          {decodeURIComponent(path)} Career Path
        </h2>
        {loading ? (
          <div style={{ textAlign: "center" }}>Loading personalized roadmap...</div>
        ) : (
          <div
            style={{
              background: "#f7faff",
              borderRadius: 14,
              padding: 24,
              boxShadow: "0 2px 16px #2563eb11",
              minWidth: 350,
              maxWidth: 700,
              overflowX: "auto",
              fontSize: "1.1rem",
              margin: "0 auto",
              display: "block",
              textAlign: "left", // Left-align text
            }}
            dangerouslySetInnerHTML={{ __html: marked.parse(roadmap) }}
          />
        )}
        <div style={{ marginTop: 36, textAlign: "center", color: "#888" }}>
          <span style={{ fontSize: 15 }}>
            <b>Tip:</b> This roadmap is generated by AI and shows the recommended learning order for your selected career path.
          </span>
        </div>
      </div>
    </div>
  );
}

export default CareerPathDetails;